# Generated by Django 5.2.5 on 2025-08-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(to='users.item'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
